spring.application.name=servico_auditoria

# MongoDB (ajuste conforme seu ambiente)
spring.data.mongodb.uri=mongodb://localhost:27017/auditoria_db

# Porta do serviço (opcional)
server.port=8085

# Springdoc OpenAPI (opcional em dev)
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger
