server.port=8000

spring.cloud.gateway.routes[0].id=auth_service_route
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/login, /auth/logout

spring.cloud.gateway.routes[1].id=monolith_service_route
spring.cloud.gateway.routes[1].uri=http://localhost:8080
spring.cloud.gateway.routes[1].predicates[0]=Path=/auth/cadastrar, /colunas/**, /comentario/**, /equipe/**, /google/**, /dashboard/**, /notificacao/**, /projeto/**, /tarefa/**, /anexo/**, /usuario/**