server.port=8000

spring.cloud.gateway.routes[0].id=auth_service_route
spring.cloud.gateway.routes[0].uri=http://localhost:8081/
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/login, /auth/logout

spring.cloud.gateway.routes[1].id=monolito_service_route
spring.cloud.gateway.routes[1].uri=http://localhost:8080/
spring.cloud.gateway.routes[1].predicates[0]=Path=/auth/cadastrar, /comentario/, /google/, /dashboard/, /notificacao/, /anexo/

spring.cloud.gateway.routes[2].id=usuario_equipe_service_route
spring.cloud.gateway.routes[2].uri=http://localhost:8083/
spring.cloud.gateway.routes[2].predicates[0]=Path=/auth/cadastrar, /auth/session, /equipe/, /usuario/

spring.cloud.gateway.routes[3].id=projeto_coluna_tarefa_service_route
spring.cloud.gateway.routes[3].uri=http://localhost:8087/
spring.cloud.gateway.routes[3].predicates[0]=Path=/colunas/, /tarefa/, /projeto/

spring.cloud.gateway.routes[4].id=comentario_service_route
spring.cloud.gateway.routes[4].uri=http://localhost:8082/
spring.cloud.gateway.routes[4].predicates[0]=Path=/comentario/**