spring.application.name=servico-comentario
server.port=8082
spring.profiles.active=dev

spring.data.mongodb.uri=${MONGODB_URI}

spring.data.mongodb.database=comentario

crypto.secret=${CRYPTO_SECRET}

api.security.token.secret=${API_SECRET_KEY}

app.validation.palavras-proibidas=${PALAVRAS_PROIBIDAS}

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.security=DEBUG