spring.application.name=servico-projeto-coluna-tarefa

usuario.service.url=http://localhost:8083

spring.data.mongodb.uri=${MONGODB_URI}
server.port=8087
api.security.token.secret=${API_SECRET_KEY}

google.client-id=${GOOGLE_CLIENT_ID}
google.client-secret=${GOOGLE_CLIENT_SECRET}

crypto.secret=${CRYPTO_SECRET}

app.validation.palavras-proibidas=${PALAVRAS_PROIBIDAS}

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.security=DEBUG

internal.api.key=bA7!qZ$r9P@sW3kE*uJm&fG#cT8^vD5%nL2xYhGZpQvB1aF4dK6jM!@sK